### ISSUE TITLE
汉化figure

### ISSUE THREAD

**Issue by Milokita** [cuhk-haosun/cuhk-haosun.github.io#20]
pls translate the figures in https://github.com/cuhk-haosun/cuhk-haosun.github.io/tree/figure-translate/assets/img/nanopore 

pls use 等线 (正文) 作为字体

**Comment by HoshinoKyouna** [comment]
Translated figures were put into "cn" folder under this directory.

**Comment by Milokita** [comment]
`Signal batch` should be `信号数据包`
至于`flowcell`的翻译交由您决断

**Comment by HoshinoKyouna** [comment]
已将signal batch替换为信号数据包，flowcell的翻译决定与此前专利翻译中保持一致
